#!/bin/bash
# Local build script for fast-api-fe

set -e

# 1. Update the frozen requirements.txt from the root uv.lock
echo "Regenerating frozen requirements.txt..."
echo "# Autogenerated from 'uv'. Do not modify this file directly. Instead modify the pyproject.toml in the project root" > requirements.txt
uv export --format requirements-txt --no-hashes --no-dev --package fast-api-fe --no-emit-workspace >> requirements.txt

# 2. Build the docker image locally
echo "Building Docker image locally..."
docker build -t fast-api-fe:latest .

echo "Local build complete."
